version: 2.1 
jobs: 
  build_tests:
    docker: 
      - image: circleci/node:12
    steps: 
      - checkout
      - run: 
          name: Install npm dependencies 
          command: |
            npm install --save
  build_docker_image:
  docker:
    - image: circleci/node:12
  steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: false
    - run:
        name: Build Docker image
        command: |
          docker build -it nodejswebapp1 -t moiz803/nodejswebapp1:latest .
          echo $DOCKER_PASSWORD | docker login -u moiz803 --password-stdin
          docker push moiz803/nodejswebapp1:latest

workflows:
  build_test:
    jobs:
      - build_test
      - build_docker_image
